### ISSUE TITLE
SyntaxError: The requested module '/node_modules/@zebra-ui/swiper/shared/utils.js' does not provide an export named 'elementTransitionEnd'

### ISSUE THREAD

**Issue by UMRzcz-831** [zebra-ui/zebra-swiper#11]
### 可复现问题的链接。或可复现问题的，在示例项目中可运行的代码片段

![image](https://github.com/zebra-ui/zebra-swiper/assets/52395980/b2791943-d9d1-4e2b-bb21-aa117418b8ba)

### 对此问题或BUG的详细描述

utils没导出这个elementTransitionEnd，可以移除掉这个引用

### 发生问题的版本号

2.2.7

**Comment by jxgzzztang** [comment]
这个问题有解决方法吗?

**Comment by zebraui** [comment]
版本2.2.8已修复
