### ISSUE TITLE
vue3下的loop适配

### ISSUE THREAD

**Issue by UMRzcz-831** [zebra-ui/zebra-swiper#12]
### 可复现问题的链接。或可复现问题的，在示例项目中可运行的代码片段

options: {
        effect: 'cards',
        loop:true,
        cardsEffect: {
          slideShadows: true,
          rotate: false,
          perSlideOffset: 10
        }
      },

### 对此问题或BUG的详细描述

![image](https://github.com/zebra-ui/zebra-swiper/assets/52395980/19fad958-a73d-495d-a1d1-ac80998d0984)
vue3环境下使用 loop:true ,报错

### 你希望的效果是怎样的

loop 下正常滑动

**Comment by zebraui** [comment]
根据你所提供的代码及步骤，并未复现此问题。

出现该问题大多数的情况为swiper组件没有正确加载。 swiper组件加载时，会监听value数据和子组件的加载。当value的长度与子组件的数量一致时，才会执行后续方法。 当出现该错误时，请仔细检查传给swiper的数据是否正确，<z-swiper v-model="list">中的list，与<z-swiper-item v-for="(item,index) in list" :key="index">中的list为同一个数据源。且确保代码逻辑没有影响到子组件的加载。

如果检查后仍有问题，可以提供更加详细的复现步骤。
