### ISSUE TITLE
自动播放在手动滑动后就不生效了

### ISSUE THREAD

**Issue by uummooq1** [zebra-ui/zebra-swiper#13]
### 可复现问题的链接。或可复现问题的，在示例项目中可运行的代码片段

:options="{autoplay:true}"

### 对此问题或BUG的详细描述

使用了自动播放，但是在手动滑动swiper之后，就不再自动播放了

### 你希望的效果是怎样的

自动播放一直生效

**Comment by zebraui** [comment]
swiper的自动切换，默认就是操作swiper后将停止。可通过disableOnInteraction参数控制。
![image](https://github.com/zebra-ui/zebra-swiper/assets/110089567/510cad4d-50ab-45e1-95ae-8dbc3f296202)
