### ISSUE TITLE
 slideNext 方法调用没有动画效果

### ISSUE THREAD

**Issue by XCooder** [zebra-ui/zebra-swiper#17]
### App平台

- [ ] H5
- [X] Android
- [ ] IOS

### 可复现问题并且在示例项目中可运行的代码片段

`<z-swiper v-model="cardList" :options="options"  ref="zSwiper">
			<z-swiper-item v-for="(item,index) in list" :key="index" class="animation">
				<view class="card-item">
					<image class="cover" :src="xxx" mode="aspectFill" />
					<view class="conten">
						<view class="title">推荐理由</view>
						<view class="desc">xxxx</view>
						<view class="btn-group">
							<view class="dislike" @click="dislike"></view>
							<view class="like" @click="like"></view>
						</view>
					</view>
				</view>
			</z-swiper-item>
</z-swiper>`
`options: {
					effect: 'cards',
					cardsEffect: {
						// rotate: false,
						perSlideOffset: 0,
						perSlideRotate: 0
					}
},`
`dislike() {
this.$refs.zSwiper.swiper.slideNext();
}`

### 对此问题或BUG的详细描述

手动调用 slideNext 方法切换卡片，没有动画效果，手指滑动会正常展示效果

### 你希望的效果是怎样的

手动调用方法也会正常展示动画效果

**Comment by zebraui** [comment]
测试未发现此问题，方法切换可能和手指滑动切换存在差异（手指滑动时有倾斜角度）。如后续仍发现有此问题，可加群提供录屏文件
