### ISSUE TITLE
通过HBuilderX引入到vue3的项目里,直接运行报错

### ISSUE THREAD

**Issue by xiaoyao20084321** [zebra-ui/zebra-swiper#18]
### 小程序平台

- [ ] H5
- [X] 微信小程序
- [ ] 支付宝小程序
- [ ] QQ小程序
- [ ] 百度小程序
- [ ] 字节小程序
- [ ] 快手小程序
- [ ] 飞书小程序

### 可复现问题并且在示例项目中可运行的代码片段

<z-swiper v-model="list" :options="options">
		<z-swiper-item v-for="(item,index) in list" :key="index">
			<view style="height: 70rpx; text-align: center;">
				{{item.text}}
			</view>
		</z-swiper-item>
	</z-swiper>

### 对此问题或BUG的详细描述

 ​"elementTransitionEnd" is not exported by "../../../../../../Users/chaoqun/Desktop/dajdjada/uni_modules/zebra-swiper/shared/utils.js", imported by "../../../../../../Users/chaoqun/Desktop/dajdjada/uni_modules/zebra-swiper/modules/controller/controller.js".​
11:41:22.450 ​Generated an empty chunk: "uni_modules/zebra-swiper/libs/events/onResize".​

**Comment by zebraui** [comment]
版本2.2.8已修复
