### ISSUE TITLE
Error: module 'uni_modules/zebra-swiper/libs/events/onResize.js' is not defined, require args is './onResize.js'

### ISSUE THREAD

**Issue by YingchenWang007** [zebra-ui/zebra-swiper#21]
### 小程序平台

- [ ] H5
- [X] 微信小程序
- [ ] 支付宝小程序
- [ ] QQ小程序
- [ ] 百度小程序
- [ ] 字节小程序
- [ ] 快手小程序
- [ ] 飞书小程序

### 可复现问题并且在示例项目中可运行的代码片段

"version": "2.2.8",

### 对此问题或BUG的详细描述

"version": "2.2.8",  报错

### 发生问题的版本号

"version": "2.2.8",

**Comment by zebraui** [comment]
测试未发现此问题，请尝试重新编译。如果在示例项目中仍会出现此问题，请提供更为详细的复现步骤
