### ISSUE TITLE
无法滚动

### ISSUE THREAD

**Issue by PPPPPPan** [zebra-ui/zebra-swiper#8]
TypeError: Cannot read property 'onTouchStart' of undefined
    at VueComponent.onTouchStart (z-swiper.js:715)
    at vendor.js:1919
    at Array.forEach (<anonymous>)
    at vendor.js:1882
    at Array.forEach (<anonymous>)
    at Object.handleEvent [as __e] (vendor.js:1882)
    at ve (af-appx.worker.min.js:24)
    at af-appx.worker.min.js:24
    at af-appx.worker.min.js:24
    at Object.batchedUpdates (af-appx.worker.min.js:24)

**Comment by Loading-m** [comment]
同报错

**Comment by kiccer** [comment]
报错+10086

**Comment by kiccer** [comment]
我把版本退到 2.2.1 之后没报错了，可以正常使用。

**Comment by kiccer** [comment]
> 我把版本退到 2.2.1 之后没报错了，可以正常使用。

加上 ```loop: true``` 时又报错了，退到 2.1.5 又好了。。

**Comment by kiccer** [comment]
我下载了demo，仔仔细细对比后，发现是我自己写错了，我把组件再封装了一层，然后内部双向绑定改写的时候把 ```:modelValue``` 错写成了 ```:value```，改正后就没有上面那些报错了！

**Comment by zebraui** [comment]
出现该问题大多数的情况为swiper组件没有正确加载。
swiper组件加载时，会监听value数据和子组件的加载。当value的长度与子组件的数量一致时，才会执行后续方法。
当出现该错误时，请仔细检查传给swiper的数据是否正确，`<z-swiper v-model="list">`中的list，与`<z-swiper-item v-for="(item,index) in list" :key="index">`中的list为同一个数据源。且确保代码逻辑没有影响到子组件的加载。

**Comment by Loading-m** [comment]
> 出现该问题大多数的情况为swiper组件没有正确加载。 swiper组件加载时，会监听value数据和子组件的加载。当value的长度与子组件的数量一致时，才会执行后续方法。 当出现该错误时，请仔细检查传给swiper的数据是否正确，`<z-swiper v-model="list">`中的list，与`<z-swiper-item v-for="(item,index) in list" :key="index">`中的list为同一个数据源。且确保代码逻辑没有影响到子组件的加载。

2022年的问题现在回答, 挖坟了属于是
