### ISSUE TITLE
vue3+vite项目运行报错

### ISSUE THREAD

**Issue by 1014156094** [zebra-ui/zebra-swiper#9]
![image](https://user-images.githubusercontent.com/16074662/235047764-851b0c08-eb89-48eb-8a81-770ddf7060a6.png)
![image](https://user-images.githubusercontent.com/16074662/235047779-96cc6173-b706-48fc-a8de-5d79b79e268f.png)
放 uni_modules 目录引入使用的

**Comment by 1014156094** [comment]
+1

**Comment by zebraui** [comment]
测试未发现此问题。2.2.8新增了关于vue3使用的示例，如果示例项目仍出现此问题，可提供代码片段。
